---
- name: Display the config
  debug:
    msg: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  tags:
   - target_user

- name: Get Target host detials
  become: true
  become_user: Ansible
  command: hostname
  register: "output"
  tags:
   - target_hostname
- name: debug output
  debug:
    msg: "This is output {{ output }}"
#- name: Execute a command using the shell module
  #become: true
  #become_user: Ansible
  #shell: hostnamectl
