---
- name: Display the config
  debug:
    msg: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  tags:
   - target_user

- name: Get Target host detials
  command: hostnamectl
  tags:
   - target_hostname
