---
- name: create user accounts
  user:
    name: "{{ item }}"
    groups: "admin,tower"
  with_items: "{{ users }}"
- name: Allow admin users to sudo without a password
  lineinfile:
     dest: "/etc/sudoers"
     state: "present"
     regexp: "^%admin"
     line: "%admin ALL=(ALL) NOPASSWD: ALL"
  tags:
    - users.yml
